spring.profiles.group:
  "local": "common,local"
---
## common Profile
spring:
  config:
    activate:
      on-profile: common
---
## common-jpa
spring:
  config:
    activate:
      on-profile: common-jpa
---
## local Profile
spring:
  config:
    activate:
      on-profile: local
# auto reload
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
# undertow
server:
  port : 8080
  undertow:
    threads:
      io: 16
      worker: 400
# Query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true
---
## local database-postgresql
spring:
  profiles:
    active: local-postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/clt
    username: acj
    password: javaBye#
  hikari:
    connection-timeout: 20000
    maximum-pool-size: 10
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
---
## Server
spring:
  config:
    activate:
      on-profile: server
# Query logging
decorator:
  datasource:
    p6spy:
      enable-logging: false
---
